---
- name: Configure DB Server
  hosts: db_server
  become: yes
  serial: 1
  tasks:
    - name: Install required Python MySQL client
      yum:
        name: python3-PyMySQL
        state: present

    - name: Install MariaDB server
      yum:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Update MariaDB config to allow remote connections
      lineinfile:
        path: /etc/my.cnf
        insertafter: '\[mysqld\]'
        line: 'bind-address = 0.0.0.0'
        regexp: '^bind-address'
      notify: restart mariadb

    - name: Create database
      community.mysql.mysql_db:
        name: kodekloud_db9
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create user with privileges
      community.mysql.mysql_user:
        name: kodekloud_roy
        password: LQfKeWWxWD
        priv: "kodekloud_db9.*:ALL"
        host: '%'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Install firewalld and python3-firewall
      yum:
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Ensure firewall allows MySQL connections
      firewalld:
        service: mysql
        state: enabled
        permanent: yes
        immediate: yes

  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted


- name: Configure App Servers
  hosts: app_servers
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - php
        - php-mysqlnd

    - name: Configure Apache to listen on port 6100
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen 6100'
      notify: restart httpd

    - name: Install firewalld and python3-firewall
      yum:
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Ensure firewall allows port 6100
      firewalld:
        port: 6100/tcp
        state: enabled
        permanent: yes
        immediate: yes

    - name: Create PHP test page
      copy:
        content: |
          <?php
          $link = mysqli_connect('172.16.239.10', 'kodekloud_roy', 'LQfKeWWxWD', 'kodekloud_db9');
          if (!$link) {
              die('Could not connect: ' . mysqli_connect_error());
          }
          echo 'App is able to connect to the database using user kodekloud_roy';
          mysqli_close($link);
          ?>
        dest: /var/www/html/index.php
        mode: 0644

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
